### ISSUE TITLE
Interesting Description

### ISSUE THREAD

**Issue by nicholaschum** [exthmui/ThemeMaker#2]
《与 Substratum 不同，对于字体和开机动画，exTHmUI 使用定制的解析方法，而不是直接替换文件。这保证了系统更新之后主题也不会失效。且由于修改了 idmap，使得叠加层安装完毕后不需要重新启动即可工作》

我明白你们提供的功能是挺有趣的，但是你们不太明白substratum的特别功能导致版本锁定是什么原因。我们从substratum造了一个功能给themers有无限的资源（resources）可以用，我们就用target来compile，然后跟framework-res来compile。

我们从substratum里已经有很多人试过超复杂的主题，AOSP装上来是很难做到没有版本锁定的问题。改变颜色的主题太容易做了。

你们所写的idmap变更其实AOSP都没有问题的，因为你compile一个overlay的时候，你这个repo没有跟target APK和framework-res一起有关系的。刷新的系统之后你可以很容易清/data/resource-cache，就不需要担心有idmap问题咯。

如果你看过CMTE，我们的系统字体功能都是跟他们一模一样，没试过直接替换文件的。 我们也试过用root来直接改变文件在stock ROM里，但是我们都能很容易改custom ROM里面的系统功能，不需要从custom ROM里直接替换文件的。

**Comment by cjybyjk** [comment]
我们知道substratum是在应用主题时编译叠加层，但是我们认为这会延长应用主题的时间，因此我们选择了将其预编译的方式
并且我们将framework中自定义资源的 id 固定化，因此可以实现不同版本系统的兼容
而 idmap 的问题是因为 Google 的安全补丁阻止了与 target apk 签名和系统签名不同的叠加层，因此我们做了些修改
对于字体，我们大量参考了 substratum 的代码，具体的位置在 https://github.com/SubstratumResources/platform_frameworks_base/commit/2374ce8ca28c742f7257cf317b63371a79ed42d9
这段文字确实有问题，我们会修正它。
感谢您的issue

We know that substratum compiles the overlay when applying the theme, but we think it will prolong the time of applying the theme, so we choose to pre-compile it.
And we fix the ID of custom resources in the framework, so we can realize the compatibility of different versions of the system
The problem with idmap is that Google's security patch prevents overlays which didn't have target APK signature or system signature, so we have made some modifications
For fonts, we refer to a lot of substratum code. The specific location is SubstratumResources/platform_frameworks_base@2374ce8
There is something wrong with this passage, and we will correct it.
Thank you for your issue

**Comment by nicholaschum** [comment]
Google's security patch enforced overlay APK to have the same signature as the target APK or have it forced in a system location, which we have also disabled long time ago. 

Obviously we had to compile overlays when applying themes because that's how you share themes on Play Store and create millions of options for overlays with mix and match, precompiling it is the same as every other vendor like Samsung, and therefore you can't distribute them on the play store which defeats the purpose of our community themes.
